Disable resolve step on merge if .gitattributes isn't present.
Modified tools/merge_upstream.sh to not attempt to resolve conflicts if
a .gitattributes file isn't present.  If no .gitattributes file is present
the script exits gracefully rather than throwing an error when trying to read
the file.

Tested:
$ git checkout -b test goog/ub-games-master
$ git rm -rf Box2D/Build
$ git commit -m 'Removed Box2D/Build.'
$ ./tools/merge_upstream.sh
... lots of output ...
Automatic merge failed; fix conflicts and then commit the result.
U       Box2D/Build/vs2012/Box2D.sln
U       Box2D/Build/vs2012/Box2D.vcxproj
U       Box2D/Build/vs2012/Box2D.vcxproj.filters
U       Box2D/Build/vs2012/FreeGLUT.vcxproj
U       Box2D/Build/vs2012/FreeGLUT.vcxproj.filters
U       Box2D/Build/vs2012/GLUI.vcxproj
U       Box2D/Build/vs2012/GLUI.vcxproj.filters
U       Box2D/Build/vs2012/HelloWorld.vcxproj
U       Box2D/Build/vs2012/HelloWorld.vcxproj.filters
U       Box2D/Build/vs2012/Testbed.vcxproj
U       Box2D/Build/vs2012/Testbed.vcxproj.filters
U       Box2D/Build/xcode5/Box2D.xcodeproj/project.pbxproj
U       Box2D/Build/xcode5/Box2D.xcodeproj/project.xcworkspace/contents.xcworkspacedata
error: 'commit' is not possible because you have unmerged files.
hint: Fix them up in the work tree,
hint: and then use 'git add/rm <file>' as
hint: appropriate to mark resolution and make a commit,
hint: or use 'git commit -a'.
fatal: Exiting because of an unresolved conflict.

Change-Id: I097d5518cce2cb6cffef00960ae15d5aad8f643a